services:
  db:
    image: postgres:15
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: manager_user
      POSTGRES_PASSWORD: manager_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: task_manager_web
    command: uv run sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=task_manager.settings
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
      - ROLLBAR_ENVIRONMENT=production

volumes:
  postgres_data: